site_name: InstructIA
site_description: A powerful Context Management System based on POD (Prompt-Oriented Development)
site_author: Vinícius Maffioli
site_url: https://digitalfen.github.io/InstructIA/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

nav:
  - Home: 
    - Overview: index.md
    - Key Features: key_features.md
    - Core Concepts: core_concepts.md
  - Usage:
    - Overview: usage.md
    - Installation: installation.md
    - Default Instructions: default_instructions.md
    - Creating Custom Instructions: custom_instructions.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde 