site_name: InstructIA
site_description: A Context Management System for AI-driven instructions and actions
site_author: DigitalFen
site_url: https://github.com/digitalfen/InstructIA

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Directory Structure: directory_structure.md
  - Rules System: rules.md
  - Base Instructions: default_instructions.md
  - Custom Instructions: custom_instructions.md
  - Core Concepts: core_concepts.md
  - Key Features: key_features.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
