site_name: Instructa Framework
site_description: A powerful framework based on POD (Prompt-Oriented Development) for automating AI-driven instructions and actions
site_author: DigitalFen
site_url: https://github.com/digitalfen/Instructa

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Project Structure: getting-started/project-structure.md
  - Core Concepts:
    - POD Development: core-concepts/pod-development.md
    - Context Management: core-concepts/context-management.md
    - Keyword Commands: core-concepts/keyword-commands.md
  - Features:
    - Prompts: features/prompts.md
    - Actions: features/actions.md
    - Internationalization: features/internationalization.md
  - Advanced:
    - Custom Instructions: advanced/custom-instructions.md
    - Extending the Framework: advanced/extending.md
  - API Reference:
    - CLI Commands: api-reference/cli-commands.md
    - Configuration: api-reference/configuration.md
  - Contributing: contributing.md
  - License: license.md 