site_name: InstructIA
site_description: A Context Management System for AI-driven instructions and actions
site_author: DigitalFen
site_url: https://github.com/digitalfen/Instructa

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Directory Structure: directory_structure.md
  - Rules System: rules.md
  - Base Instructions: default_instructions.md
  - Custom Instructions: custom_instructions.md
  - Core Concepts: core_concepts.md
  - Key Features: key_features.md
  - Contributing: contributing.md
  - License: license.md 